### ISSUE TITLE
Adapter does not support custom directory

### ISSUE THREAD

**Issue by ghost** [waterlinejs/sqlite3-adapter#15]
As stated by the API I assumed that the adapter will allow to set a custom location for my sqlite3 file, but it failed when I was trying it.

After some debugging I saw that `adapter.js` hardcoded the filepath

```
 fs.mkdir('.tmp', () => {
      this.connections.set(connection.identity, {
        identity: connection.identity,
        schema: this.buildSchema(connection, collections),
        collections: collections,
        knex: Knex({
          client: 'sqlite3',
          connection: {
            filename: '.tmp/' + connection.identity + '.sqlite'
          },
          debug: process.env.WATERLINE_DEBUG_SQL || connection.debug
        })
      })
      cb()
    })
```

Is this a desired behaviour that all db files will be stored in `.tmp` ?

**Comment by AGvin** [comment]
Hi @tjwebb,

Can You publish new version in NPM with current changes?
(Now package.json "main" property follow to "dist/adapter" with old code, and "dist" compiled only at publishing,  so repository can't be used directly, without adding "postinstall" script )

Regards,
Viacheslav
