### ISSUE TITLE
Error using adapter: "waterline-sqlite3", in SailsJS v0.11 

### ISSUE THREAD

**Issue by kiksy** [waterlinejs/sqlite3-adapter#2]
Trying to add Sqlite3 adaptor to SailsJS project, on 'sails lift' I get:

`error: There was an error attempting to require("waterline-sqlite3")
error: Is this a valid Sails/Waterline adapter?  The following error was encountered ::
error: Error: Cannot find module '/var/www/project/node_modules/waterline-sqlite3/node_modules/sqlite3/lib/binding/node-v47-linux-x64/node_sqlite3.node'`

My connections.js is 

`
sqlitedb: {

```
    adapter: "waterline-sqlite3",
    /**
     * Database instance type. Specify whether to store the database on disk
     * or in memory.
     */
    type: 'disk', // or 'memory'

    /**
     * Location of file if type='disk'
     */
    filename: './tmp/db.sqlite',

    /**
     * Set to true to output SQL queries
     */
    debug: false
}
```

`

Looking in 

`/var/www/project/node_modules/waterline-sqlite3/node_modules/sqlite3/lib/binding/`

I see a 

`node-v14-linux-x64/`

dir ,whereas it seems its looking for

`node-v47-linux-x64/`

npm version is 3.3.6 , node version is 5.0.0

**Comment by kiksy** [comment]
As an update to this, in:

`/var/www/project/node_modules/sqlite3/lib/binding/`

I have a 

`node-v47-linux-x64` 

directory. Manually copying that to: 

`/var/www/project/node_modules/waterline-sqlite3/node_modules/sqlite3/lib/binding/`

Removes the error.

**Comment by tjwebb** [comment]
That's really strange. What version of node are you running?

**Comment by eyasliu** [comment]
your sails app folder and package.json for install waterline-sqlite3 file path is not a same file

**Comment by ducky427** [comment]
I was getting a similar error. Looking at the `npm install` log, I solved my problem with this [SO](https://stackoverflow.com/questions/18136746/npm-install-failed-with-cannot-run-in-wd) post.

Hope it helps.

**Comment by kiksy** [comment]
@ducky427 Deleting my node_modules and then running :

`npm install --unsafe-perm`

Removes the error. I guess this is some permissions issue, I'm running everything as root right now, including 

`sails lift`
